/*
===============================================================================
FUNCTION: fn_state_revenue
===============================================================================

Question:
    Create a function that accepts a seller state and returns the
    total revenue generated by sellers in that state.

Reused Pattern:
    Seller revenue analysis grouped by seller state.

Input:
    Seller state.

Output:
    Total revenue generated in that state.

===============================================================================
*/

CREATE OR REPLACE FUNCTION fn_state_revenue(
    p_seller_state VARCHAR
)
RETURNS NUMERIC
LANGUAGE SQL
AS $$
    SELECT
        COALESCE(
            ROUND(
                SUM(oi.price)::numeric,
                2
            ),
            0
        )

    FROM sellers AS s

    INNER JOIN order_items AS oi
        ON s.seller_id = oi.seller_id

    WHERE
        s.seller_state = p_seller_state;
$$;


/*
===============================================================================
TEST THE FUNCTION
===============================================================================
*/

SELECT fn_state_revenue('SP');