/*
===============================================================================
08_FUNCTIONS — FUNCTION SUMMARY
===============================================================================

Project:
    Ecommerce Sales Analytics

Purpose:
    This file documents the reusable PostgreSQL functions created for
    common ecommerce business analysis.

Functions:
    01. fn_customer_lifetime_value
    02. fn_monthly_sales
    03. fn_top_selling_products
    04. fn_average_delivery_days
    05. fn_customer_order_count
    06. fn_state_revenue

===============================================================================
*/


/*
===============================================================================
01. fn_customer_lifetime_value
===============================================================================

Business Question:
    How much has a specific customer spent throughout their lifetime?

Input:
    p_customer_unique_id VARCHAR

Returns:
    NUMERIC

Description:
    Calculates the total amount spent by a customer across all of their
    orders.

Example:
*/

SELECT fn_customer_lifetime_value(
    'CUSTOMER_UNIQUE_ID'
);


/*
===============================================================================
02. fn_monthly_sales
===============================================================================

Business Question:
    How much revenue was generated during a specific month?

Input:
    p_month DATE

Returns:
    NUMERIC

Description:
    Calculates total sales revenue for the month supplied as the input.

Example:
*/

SELECT fn_monthly_sales(
    '2018-01-01'
);


/*
===============================================================================
03. fn_top_selling_products
===============================================================================

Business Question:
    What are the top-selling products within a specific product category?

Input:
    p_product_category VARCHAR

Returns:
    TABLE

Description:
    Calculates product-level revenue for the selected category, ranks
    products by revenue, and returns the top 3 products.

Example:
*/

SELECT *
FROM fn_top_selling_products(
    'beleza_saude'
);


/*
===============================================================================
04. fn_average_delivery_days
===============================================================================

Business Question:
    What is the average delivery time for customers in a specific state?

Input:
    p_customer_state VARCHAR

Returns:
    NUMERIC

Description:
    Calculates the average number of days between order approval and
    customer delivery for the selected customer state.

Example:
*/

SELECT fn_average_delivery_days(
    'SP'
);


/*
===============================================================================
05. fn_customer_order_count
===============================================================================

Business Question:
    How many orders has a specific customer placed?

Input:
    p_customer_unique_id VARCHAR

Returns:
    INTEGER

Description:
    Counts the distinct orders associated with the selected customer.

Example:
*/

SELECT fn_customer_order_count(
    'CUSTOMER_UNIQUE_ID'
);


/*
===============================================================================
06. fn_state_revenue
===============================================================================

Business Question:
    How much revenue was generated by sellers in a specific state?

Input:
    p_seller_state VARCHAR

Returns:
    NUMERIC

Description:
    Calculates total revenue generated by sellers operating in the
    selected state.

Example:
*/

SELECT fn_state_revenue(
    'SP'
);


/*
===============================================================================
FUNCTION SUMMARY
===============================================================================

Function                         Input                  Output
-------------------------------------------------------------------------------
fn_customer_lifetime_value      customer_unique_id    NUMERIC
fn_monthly_sales                 month                 NUMERIC
fn_top_selling_products         product_category      TABLE
fn_average_delivery_days        customer_state        NUMERIC
fn_customer_order_count         customer_unique_id    INTEGER
fn_state_revenue                seller_state          NUMERIC

===============================================================================
*/