/*
===============================================================================
Question    : Revenue by Product Category
Description : Calculates the total revenue generated by each product category
              and displays the categories in descending order of revenue.
===============================================================================
*/

SELECT
    product_category_name_english AS product_category,
    ROUND(SUM(price), 2) AS total_revenue
FROM vw_sales
GROUP BY
    product_category_name_english
ORDER BY
    total_revenue DESC;


/*
===============================================================================
Question    : Revenue by State
Description : Calculates the total revenue generated by each customer state
              and displays the states in descending order of revenue.
===============================================================================
*/

SELECT
    customer_state AS state,
    ROUND(SUM(price), 2) AS total_revenue
FROM vw_sales
GROUP BY
    customer_state
ORDER BY
    total_revenue DESC;



    
/*
===============================================================================
Question    : Revenue by Seller
Description : Calculates the total revenue generated by each seller
              and displays the sellers in descending order of revenue.
===============================================================================
*/

SELECT
    seller_id,
    ROUND(SUM(price), 2) AS total_revenue
FROM vw_sales
GROUP BY
    seller_id
ORDER BY
    total_revenue DESC;


/*
===============================================================================
Question    : Monthly Revenue
Description : Calculates the total revenue generated for each month and
              displays the monthly revenue in chronological order.
===============================================================================
*/

SELECT
    DATE_TRUNC('month', order_purchase_timestamp) AS sales_month,
    ROUND(SUM(price), 2) AS total_revenue
FROM vw_sales
GROUP BY
    sales_month
ORDER BY
    sales_month;

    /*
===============================================================================
Question    : Monthly Revenue
Description : Calculates the total revenue generated for each month and
              displays the monthly revenue in chronological order.
===============================================================================
*/

SELECT
    DATE_TRUNC('month', order_purchase_timestamp) AS sales_month,
    ROUND(SUM(price), 2) AS total_revenue
FROM vw_sales
GROUP BY
    sales_month
ORDER BY
    sales_month;


/*
===============================================================================
Question    : Average Order Value
Description : Calculates the average value of an order by first computing the
              total value of each order and then averaging those totals.
===============================================================================
*/

SELECT
    ROUND(AVG(order_value), 2) AS average_order_value
FROM
(
    SELECT
        order_id,
        SUM(price) AS order_value
    FROM vw_sales
    GROUP BY
        order_id
) AS order_totals;

/*
===============================================================================
Question    : Average Delivery Days
Description : Calculates the average number of days taken to deliver
              completed orders.
===============================================================================
*/

SELECT
    ROUND(AVG(delivery_days)::numeric, 2) AS average_delivery_days
FROM vw_delivery
WHERE order_status = 'delivered';

/*
===============================================================================
Question    : Orders by Status
Description : Calculates the total number of orders for each order status and
              displays the results in descending order.
===============================================================================
*/

SELECT
    order_status,
    COUNT(order_id) AS total_orders
FROM vw_orders
GROUP BY
    order_status
ORDER BY
    total_orders DESC;

    
/*
===============================================================================
Question    : Payment Type Distribution
Description : Calculates the number of unique orders for each payment type and
              displays the payment methods in descending order of usage.
===============================================================================
*/

SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM vw_payments
GROUP BY
    payment_type
ORDER BY
    total_orders DESC;

/*
===============================================================================
Question    : Top Product Categories
Description : Calculates the total number of products sold for each product
              category and displays the categories in descending order.
===============================================================================
*/

SELECT
    product_category_name_english AS product_category,
    COUNT(product_id) AS products_sold
FROM vw_sales
GROUP BY
    product_category_name_english
ORDER BY
    products_sold DESC;

/*
===============================================================================
Question    : Top Customer States
Description : Calculates the total number of unique customers in each state
              and displays the states in descending order of customer count.
===============================================================================
*/

SELECT
    customer_state,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM vw_customers
GROUP BY
    customer_state
ORDER BY
    total_customers DESC;