/*
===============================================================================
Question    : Revenue by Product Category
Description : Calculates the total revenue generated by each product category
              and displays the categories in descending order of revenue.
===============================================================================
*/

SELECT
    product_category_name_english AS product_category,
    ROUND(SUM(price), 2) AS total_revenue

FROM vw_sales

GROUP BY
    product_category_name_english

ORDER BY
    total_revenue DESC;


    /*
/*
===============================================================================
Question    : Revenue by State
Description : Calculates the total revenue generated by each customer state
              and displays the states in descending order of revenue.
===============================================================================
*/

SELECT
    customer_state AS state,
    ROUND(SUM(price), 2) AS total_revenue

FROM vw_sales

GROUP BY
    customer_state

ORDER BY
    total_revenue DESC;



    
/*
===============================================================================
Question    : Revenue by Seller
Description : Calculates the total revenue generated by each seller
              and displays the sellers in descending order of revenue.
===============================================================================
*/

SELECT
    seller_id,
    ROUND(SUM(price), 2) AS total_revenue

FROM vw_sales

GROUP BY
    seller_id

ORDER BY
    total_revenue DESC;


/*
===============================================================================
Question    : Monthly Revenue
Description : Calculates the total revenue generated for each month and
              displays the monthly revenue in chronological order.
===============================================================================
*/

SELECT
    DATE_TRUNC('month', order_purchase_timestamp) AS sales_month,

    ROUND(SUM(price), 2) AS total_revenue

FROM vw_sales

GROUP BY
    sales_month

ORDER BY
    sales_month;

    /*
===============================================================================
Question    : Monthly Revenue
Description : Calculates the total revenue generated for each month and
              displays the monthly revenue in chronological order.
===============================================================================
*/

SELECT
    DATE_TRUNC('month', order_purchase_timestamp) AS sales_month,

    ROUND(SUM(price), 2) AS total_revenue

FROM vw_sales

GROUP BY
    sales_month

ORDER BY
    sales_month;