/*
===============================================================================
Question    : Customers with No Orders
Description : Retrieves customers who have never placed an order by using a
              LEFT JOIN between customers and orders.
===============================================================================
*/

SELECT
    c.customer_id,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE
    o.order_id IS NULL;

/*
===============================================================================
Question    : Sellers with Total Revenue
Description : Retrieves sellers with their total revenue by using a
              LEFT JOIN between sellers and orders.
===============================================================================
*/

SELECT
    s.seller_id,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY
    s.seller_id
ORDER BY
    total_revenue DESC;

/*
===============================================================================
Question    : Orders with Payment Details
Description : Retrieves each order along with its payment information,
              including payment type, installments, and payment value.
===============================================================================
*/

SELECT
    o.order_id,
    o.order_status,
    op.payment_type,
    op.payment_installments,
    op.payment_value
FROM orders AS o
INNER JOIN order_payments AS op
    ON o.order_id = op.order_id;

/*
===============================================================================
Question    : Top Customers by Spending
Description : Calculates the total amount spent by each customer and displays
              the highest spending customers.
===============================================================================
*/

SELECT
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    ROUND(SUM(oi.price),2) AS total_spent
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_unique_id,
    c.customer_city,
    c.customer_state
ORDER BY
    total_spent DESC;

/*
===============================================================================
Question    : Customer Purchase Summary
Description : Provides a purchase summary for each customer, including total
              orders, total spending, and average order value.
===============================================================================
*/

SELECT
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.price), 2) AS total_spent,
    ROUND(
        SUM(oi.price) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_unique_id,
    c.customer_city,
    c.customer_state
ORDER BY
    total_spent DESC;/*
===============================================================================
Question    : Products Never Sold
Description : Retrieves products that have never been sold by using a LEFT JOIN
              between products and sales.
===============================================================================
*/

SELECT
    p.product_id,
    p.product_category_name_english AS product_category,
    p.product_weight_g
FROM vw_products AS p
LEFT JOIN vw_sales AS s
    ON p.product_id = s.product_id
WHERE
    s.product_id IS NULL;


/*
===============================================================================
Question    : Orders with Customer Details
Description : Retrieves each order along with the customer information who
              placed the order.
===============================================================================
*/

SELECT
    o.order_id,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    o.order_status,
    o.order_purchase_timestamp
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id;

/*
===============================================================================
Question    : Orders with Review Scores
Description : Retrieves each order along with its review information,
              if available.
===============================================================================
*/

SELECT
    o.order_id,
    o.order_status,
    orv.review_score,
    orv.review_comment_title,
    orv.review_creation_date
FROM orders AS o
LEFT JOIN order_reviews AS orv
    ON o.order_id = orv.order_id;

/*
===============================================================================
Question    : Revenue by Seller State
Description : Calculates the total revenue generated by sellers in each state
              and displays the states in descending order of revenue.
===============================================================================
*/

SELECT
    s.seller_state,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY
    s.seller_state
ORDER BY
    total_revenue DESC;

/*
===============================================================================
Question    : Complete Order Details
Description : Retrieves a comprehensive view of each order by combining
              customer, product, seller, payment, and review information.
===============================================================================
*/

SELECT
    o.order_id,
    o.order_purchase_timestamp,
    o.order_status,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    p.product_id,
    p.product_category_name,
    s.seller_id,
    s.seller_state,
    oi.price,
    oi.freight_value,
    op.payment_type,
    op.payment_value,
    orv.review_score

FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
INNER JOIN products AS p
    ON oi.product_id = p.product_id
INNER JOIN sellers AS s
    ON oi.seller_id = s.seller_id
INNER JOIN order_payments AS op
    ON o.order_id = op.order_id
LEFT JOIN order_reviews AS orv
    ON o.order_id = orv.order_id;