/*
===============================================================================
Question    : Products Never Sold
Description : Retrieves products that have never been sold by using a LEFT JOIN
              between products and sales.
===============================================================================
*/

SELECT
    p.product_id,
    p.product_category_name_english AS product_category,
    p.product_weight_g
FROM vw_products AS p
LEFT JOIN vw_sales AS s
    ON p.product_id = s.product_id
WHERE
    s.product_id IS NULL;


/*
===============================================================================
Question    : Orders with Customer Details
Description : Retrieves each order along with the customer information who
              placed the order.
===============================================================================
*/

SELECT
    o.order_id,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    o.order_status,
    o.order_purchase_timestamp
FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id;

/*
===============================================================================
Question    : Orders with Review Scores
Description : Retrieves each order along with its review information,
              if available.
===============================================================================
*/

SELECT
    o.order_id,
    o.order_status,
    orv.review_score,
    orv.review_comment_title,
    orv.review_creation_date
FROM orders AS o
LEFT JOIN order_reviews AS orv
    ON o.order_id = orv.order_id;

/*
===============================================================================
Question    : Revenue by Seller State
Description : Calculates the total revenue generated by sellers in each state
              and displays the states in descending order of revenue.
===============================================================================
*/

SELECT
    s.seller_state,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY
    s.seller_state
ORDER BY
    total_revenue DESC;

/*
===============================================================================
Question    : Complete Order Details
Description : Retrieves a comprehensive view of each order by combining
              customer, product, seller, payment, and review information.
===============================================================================
*/

SELECT
    o.order_id,
    o.order_purchase_timestamp,
    o.order_status,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    p.product_id,
    p.product_category_name,
    s.seller_id,
    s.seller_state,
    oi.price,
    oi.freight_value,
    op.payment_type,
    op.payment_value,
    orv.review_score

FROM customers AS c
INNER JOIN orders AS o
    ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
INNER JOIN products AS p
    ON oi.product_id = p.product_id
INNER JOIN sellers AS s
    ON oi.seller_id = s.seller_id
INNER JOIN order_payments AS op
    ON o.order_id = op.order_id
LEFT JOIN order_reviews AS orv
    ON o.order_id = orv.order_id;